name: PR - Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shufl-web
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules and Build for Production
      run: |
        npm i
        npm run build:prod
    - name: Run Tests
      run: npm run test
    - name: Archive Test Screenshots
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Screenshots
        path: shufl-web/cypress/screenshots/
        retention-days: 5
    - name: Archive Test Videos
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Videos
        path: shufl-web/cypress/videos/
        retention-days: 5
